els0r/goProbe

pkg/goDB/GPFile.go, pkg/goDB/db_writer.go, pkg/goDB/encoder.go, pkg/goDB/lz4/lz4.go
This prepares us for usage of other compression algorithms.
=> generalize data compression methods for GP File

pkg/capture/capture_pfring_linux.go, pkg/capture/pfring_source_linux.go
IMHO this should be disabled by default (it's proprietary anyway)...
=> Make pfring opt-in during compilation

go.mod, go.sum
=> Update golang.org/x/net to address potential vulnerabilities

go.mod, go.sum, pkg/goDB/DBWorkManager.go, pkg/goDB/encoder/encoder.go, pkg/goDB/encoder/encoder_test.go, pkg/goDB/encoder/lz4/lz4.go, pkg/goDB/encoder/lz4cust/lz4cust.go, pkg/goDB/encoder/null/null.go, pkg/goDB/encoder/zstd/zstd.go, pkg/goDB/storage/gpfile/gpdir.go, pkg/goDB/storage/gpfile/gpfile.go, pkg/goDB/storage/gpfile/gpfile_test.go, pkg/goDB/storage/gpfile/options.go
=> 56 replace gozstd with zstd system library in line with lz4

pkg/goDB/storage/gpfile/gpdir.go, pkg/goDB/storage/gpfile/gpfile.go, pkg/goDB/storage/gpfile/gpfile_test.go
... and consistent data on consecutive writes. Closes #60 .
=> Support atomic writes for GPDirs

pkg/types/hashmap/list.go
=> Fix panic during Flatten() if hashmap is empty

pkg/capture/GPClassify.go, pkg/capture/GPFlow.go, pkg/capture/GPPacket.go, pkg/capture/GPPacket_test.go, pkg/capture/flow_log.go
=> Revise packet classification logic and add tests / benchmarks

pkg/capture/GPPacket.go, pkg/capture/GPPacket_test.go
=> Add 443/UDP to list of common ports for source port merging

pkg/types/hashmap/hashmap.go, pkg/types/hashmap/hashmap_test.go
=> 76 use seeded hash for hashmap

examples/analyze-meta/main.go, pkg/goDB/db_writer.go, pkg/goDB/db_writer_test.go, pkg/goDB/storage/gpfile/gpdir.go, pkg/goDB/storage/gpfile/gpfile.go, pkg/types/hashmap/hashmap_test.go, pkg/types/hashmap/iterator.go, pkg/types/keyval.go
Issue boiled down to a combination of multiple smaller regressions introduced in #60 and #76 . Fixes were trivial, added new tests to cover for similar scenarios.
Closes #96
=> Panic during DB writeout (invalid IPv4 / IPv6 key) due to multiple regressions

pkg/capture/capture.go
Moves the call to `Free()` out of the processing routine (where it doesn't belong anyway) into the closing state handler.
Closes #97
=> [bugfix] Move capture handler call Free() to end of closing state to avoid race condition

pkg/logging/init.go, pkg/logging/logger.go, pkg/logging/logging_test.go, pkg/logging/plain-handler.go
A glorified `fmt.Fprintln()` at your service.
=> [feature] Plain logger for simple CLI logging

.github/workflows/build-packages.yml, .github/workflows/pr-naming-rules.yml
Should enforce the rules defined in #90 .
Closes #90
=> [feature] Create PR naming rule (enforcement) GitHub action

pkg/results/result.go, pkg/results/sort.go
@els0r This should do (E2E test confirms consistency) and be as generic as can be.
Closes #113
=> [bugfix] Extend deterministic fallback sorting for result rows

cmd/gpctl/cmd/root.go, pkg/api/client/client.go, pkg/api/goprobe/server/server.go, pkg/api/util.go
=> [feature] API: support for UNIX sockets in client and server libraries

go.mod, go.sum
Quick PR to update slimcap to incorporate changes in https://github.com/fako1024/slimcap/issues/50
=> [feature] Update slimcap dependency (issue #50)

cmd/global-query/pkg/distributed/query.go, cmd/goQuery/cmd/admin.go, cmd/goQuery/cmd/list.go, cmd/goQuery/cmd/root.go, cmd/goQuery/cmd/version.go, cmd/goQuery/pkg/conf/conf.go, pkg/e2etest/types.go, pkg/goDB/DBWorkManager.go, pkg/goDB/Query.go, pkg/goDB/engine/query.go, pkg/goDB/info/interfaces.go, pkg/goDB/metadata.go, pkg/goDB/storage/gpfile/gpdir.go, pkg/goDB/storage/storage.go, pkg/query/args.go, pkg/query/time.go, pkg/results/TablePrinter.go, pkg/results/result.go
=> [feature] List target for goQuery using GPDir metadata

pkg/e2etest/e2e_test.go, pkg/e2etest/types.go
This was easier than anticipated. And I love how this worked out, with the list target (which is tested for all E2E subtests now) we have yet another cross-check for the overall counters, including V4 / V6 fractions (which was not tracked / cross-checked before).
Closes #144
=> [feature] Extend E2E test suite to always cross-check interface --list target

cmd/gpctl/cmd/status.go, pkg/capture/capture.go, pkg/capture/capture_manager.go, pkg/capture/capture_test.go, pkg/capture/capturetypes/parsing_error.go, pkg/capture/capturetypes/status.go, pkg/capture/flow.go, pkg/capture/packet_test.go, pkg/e2etest/e2e_test.go
For details, see explanation in #178 :  https://github.com/els0r/goProbe/issues/178#issuecomment-1689495584
Closes #178
=> [feature] Redesign packet parsing error tracking and allow extraction

.github/workflows/build-packages.yml, .github/workflows/go.yml, go.mod, go.sum, pkg/e2etest/types.go
Includes all new features and fixes from slimcap (including the ones not yet merged).
Closes #198
=> [feature] Bump slimcap to newest commit and update CI / CD pipelines

go.mod, go.sum
Updates slimcap to first release.
=> [feature] Bump slimcap dependency to v1.0.0

pkg/api/server/server.go
=> [bugfix] Set Gin release / debug mode correctly

.github/workflows/build-packages.yml
=> [bugfix] Add (missing) gpctl to CD / package build pipeline

go.mod, go.sum
As discussed, first preview at new version.
=> [feature] Bump slimcap to alpha v1.0.1 for performance improvements

pkg/capture/capture_test.go
Identified as timing issue on slow GitHub workers and fixed by increasing timeouts for deadlock detection.
Closes #242
=> [bugfix] Extend logging for capture deadlock detection test

go.mod, go.sum
Includes latest performance improvement and security & bug fixes from upstream `slimcap`.
Closes #231
=> [bugfix][feature] Bump slimcap to release v1.0.1

pkg/goDB/engine/query.go
=> [bugfix] Limit output table to length / number of filtered results

cmd/gpctl/cmd/config.go
=> [feature] Increase gpctl default API request timeout to 10s

pkg/capture/capture.go, pkg/capture/capturetypes/parsing_error.go, pkg/capture/capturetypes/parsing_error_test.go, pkg/capture/metrics.go, pkg/e2etest/e2e_test.go, pkg/e2etest/types.go
=> [bugfix][feature] Fix E2E test components for Prometheus metrics and improve packet / parsing issue counters

go.mod, go.sum
=> [feature] Bump slimcap to v1.0.4

pkg/formatting/format.go, pkg/results/TablePrinter.go
=> [feature] GoQuery: print small numbers more legibly in table output

pkg/types/columns.go
=> [feature] GoQuery: rename hostname attribute to host in table output

cmd/gpctl/cmd/root.go
=> [bugfix] Actually handle default config file for gpctl

pkg/query/options.go, pkg/version/version.go
Drive-by: Add functional options for building queries more easily.
=> [bugfix] Fix potential crash when building version string

pkg/e2etest/e2e_test.go
Adds:
- E2E run against local `goProbe` API
- E2E run against local `goProbe` API via streaming
=> [feature] Extend E2E tests to all possible modes

cmd/global-query/cmd/server.go, go.mod, go.work.sum, plugins/contrib/go.mod
=> [bugfix] Migrate plugins/contrib submodule to v4 path

go.mod
=> [bugfix] Enforce specific commit for plugins/contrib submodule

pkg/e2etest/e2e_test.go
Quick-shot fix to reduce flakiness of E2E tests (seems that the fixed port 11130 is not guaranteed to be available, so we make it use any available one). Also fixes a few (new) Linter-inspired fixes based on most recent Go versions.
Rebasing the presentation branch to this after merging to main should fix the failed action.
=> [bugfix] Improve resilience of E2E test to minimize flaky CI builds

pkg/goDB/engine/query_linux.go, pkg/types/hashmap/hashmap.go, pkg/types/hashmap/hashmap_test.go
=> [bugfix] Fix a (rare) bug in the hashmap merge logic causing inconsistent output in certain situations

pkg/api/query.go, pkg/api/query_api_ops.go
Modifies the existing `/_query/validate` endpoint by allowing additional validation to be injected.
The distributed API of global-query makes use of that to validate that the `query_hosts` parameter is set. This was previously done inside the query controller, hence returning a 500 error.
This change makes the error 422, pointing to the offending parameter (like for the rest of the query.Args).
Closes #398
=> [feature] Validation endpoint specific to distributed querying
