.drone.yml, .gitignore, CHANGES, README.md, addon/Makefile, addon/deb-control, addon/goprobe.service, addon/goprobe.targets, addon/postinst, addon/postrm, addon/preinst, cmd/goProbe/config/config_test.go, cmd/goquery_completion/cmd.go, go.mod, go.sum, pkg/query/defaults.go
I cleaned up the Makefile in regards to the package paths etc. I think the product is mature and simple enough to actually adhere to OS defaults, such as using /bin and /etc and the DB path (defaults to /usr/local/goProbe/db) without any prefixes, which not only simplifies the deployment but, most importantly, removes the necessity of building the systemd script dynamically.
As a result of this simplification, the Makefile now contains a `make deb` target that creates a regular .deb file which can be installed on any amd64 Debian / Ubuntu system. After adapting the example /etc/goprobe.conf.example file to /etc/goprobe.conf, the systemd service can be started right away.
=> improve packagingand add.deb Makefile target

CHANGES, README.md, addon/Dockerfile.debpkg, addon/Makefile, addon/deb-control
- Significant simplification of Debian package build pipeline
- Reduction of potential build issues due to GLIBC mismatches between build & deployment hosts
- More flexibility regarding target OS / version (should always support stable + previous Debian versions and _any_ Go version by simply setting one environment variable)
- Update to README to cover changes
=> Improve Debian package build pipeline

go.mod, go.sum, pkg/goDB/engine/query.go, pkg/goDB/info/hostid.go, pkg/goDB/info/hostid_default.go, pkg/goDB/info/hostid_linux.go, pkg/goDB/info/info.go, pkg/goDB/info/info_test.go
Replaces external dependency on `machineid` with custom implementation, using available options on `linux` systems. In any case, should retrieval fail, a fallback ID will be generated (on first access) and stored in the main directory of the goDB in question.
Implementations for other OSes can easily be added in the future if required.
Closes #69
=> 69 revisit hostid generation

.github/workflows/build-packages.yml
Adds binary upload, automatic release notes creation (for an example see [here](https://github.com/fako1024/gatt/releases/tag/v1.0.3)) and first shot at `rpm` build pipeline. Once merged I'll create another test tag to see if all works well, then close the issue manually.
=> 90 improve ci cd pipeline

.github/workflows/build-packages.yml
Apparently the `downloaded-artifacts` adds the _name_ of the upload pipeline into its path, so during the last release attempt none of the created files were matched / uploaded to the release note. This should fix it (although we can only be sure after the next test release / tag).
=> Fix (autogenerated) release artifact paths

pkg/goDB/DBWorkManager.go, pkg/goDB/godb_test.go
Trivial fix, workload counter is now atomic (since this is called very rarely even for large queries performance is not an issue).
Closes #94
=> Make DB workload counter atomic and align type with overall counter

cmd/goConvert/goConvert.go, cmd/goProbe/config/config.go, cmd/goProbe/goProbe.go, cmd/legacy/main.go, pkg/goDB/db_writer.go, pkg/goDB/db_writer_test.go, pkg/goDB/storage/gpfile/gpdir.go, pkg/goDB/storage/gpfile/gpfile.go, pkg/goDB/storage/gpfile/gpfile_test.go, pkg/goDB/storage/gpfile/options.go, pkg/goprobe/writeout/handler.go
Couldn't resist and added configurability throughout the chain and for all tools / binaries. Default is now `0644` (files) and `0755` (directories) so that default behavior is unchanged and permissive, as discussed.
Closes #85
=> [feature][security] Unify permissions and add configurability goDB data

cmd/goQuery/commands/root.go
What I've done:
- Replaced all manual error handling / output in the `cobra` entrypoint function to simply return the error to the caller
- Handle any error from that function in `Execute()`, using "our" logger with its `Fatalf()` method
- Initialize our logger directly in `init()` instead of via `cobra` (to ensure it's already initialized if the error occurs before `cobra` can call the initializer)
@els0r For now I've kept this a draft because there are two open questions IMHO:
```
ts=2023-04-11T11:23:51.976+02:00 level=fatal msg="Error running query: failed to prepare query: failed to parse query type: Unknown attribute name: 'protod'" version=872abf81
```
TBH I don't think that someone running a CLI expects a "logger" style response but rather something like:
```
Error running query: …
```
=> [bugfix] Straighten out command-line error handling

pkg/results/result.go, pkg/results/sort.go
@els0r Simple solution / proposal: Whenever two flows have equal counters relevant / chosen for sorting we "sub-sort" them by their attributes, following the requested order. That way results are always deterministic without breaking anything.
=> [bugfix] Enforce deterministic result order for flows / entries with identical counters

go.mod, go.sum, pkg/capture/capture.go, pkg/capture/capture_test.go, pkg/e2etest/e2e_test.go
Corresponding upstream changes: https://github.com/fako1024/slimcap/pull/49
In addition to these I've also added synchronization for the termination of the `process()` routine. Strictly speaking it might not be necessary but I wanted to make sure we don't run into some weird edge case when e.g. updating existing interfaces (I'm thinking about the old `process()` still consuming from the ring buffer the "new" `process()` has already started to consume from (after all it's probably the same underlying kernel memory are, so who knows what might happen).
Now, when a `Capture` closes, it's handle is closed and processing is terminated for sure.
Closes #126
=> [bugfix] Fix race condition when closing mock captures

cmd/gpctl/cmd/config.go, cmd/gpctl/cmd/status.go, go.mod, go.sum, pkg/api/goprobe/api.go, pkg/api/goprobe/client/status.go, pkg/api/goprobe/server/status.go, pkg/capture/capture.go, pkg/capture/capture_manager.go, pkg/capture/capturetypes/status.go, pkg/formatting/format.go, pkg/formatting/format_test.go, pkg/results/TablePrinter.go
Now includes the runtime totals for received and processed. Looks as follows:
```
╭───────────────────────────────────────────────────────────────────╮
│                        Interface Statuses                         │
├───────┬──────────┬────────────┬───────────┬─────────────┬─────────┤
│       │    total │            │     total │             │         │
│ iface │ received │ + received │ processed │ + processed │ dropped │
├───────┼──────────┼────────────┼───────────┼─────────────┼─────────┤
│ eth0  │  58.38 k │   514.00   │   58.38 k │    513.00   │ 0       │
│ eth1  │   0.00   │     0.00   │    0.00   │      0.00   │ 0       │
╰───────┴──────────┴────────────┴───────────┴─────────────┴─────────╯
2/2 interfaces active
Totals:
Last writeout: 2023-06-21 03:35:00 (54s ago)
Packets …
```
=> [feature] Add totals to gpctl status and print results of commands as table

pkg/logging/init.go, pkg/logging/logging_test.go
Adds the `WithFileOutput` option to the logger as a convenience wrapper around `WithOutput`.
=> [feature] Support for logging to file

cmd/goConvert/goConvert.go, pkg/goDB/DBWorkManager.go, pkg/goDB/db_writer_test.go, pkg/goDB/godb_test.go, pkg/types/hashmap/aggregate.go, pkg/types/hashmap/hashmap_test.go, pkg/types/hashmap/list.go
This was even easier than anticipated (it would have been one line of code if it weren't for the fact that we _still_ want to support having IPv4 / IPv6 conditionals even if the attributes don't include any IPs).
Relevant commit is b821cd65b2f9b984bde686c419f30539e2f9d2b8 , the rest is cosmetics.
Output now:
```
goQuery -d /tmp/db_out2  -f "2006-03-01T00:00:00Z" list 
iface    packets     traffic      flows                   from                     to
-----    -------     -------      -----                   ----                     --
eth0    19.39 G    19.55 TB    50.28 M    2016-02-29 23:17:00    2020-04-10 10:18:12
Total    19.39 G    19.55 TB    50.28 M
goQuery -d /tmp/db_out2  -f "2006-03-01T00:00:00Z" -i eth0 iface
packets  packets             bytes     bytes        
iface …
```
=> [bugfix] Aggregate IPv4 and IPv6 in queries without IP attributes

cmd/goQuery/cmd/root.go, cmd/goQuery/pkg/conf/conf.go, pkg/query/statement.go, pkg/results/result.go, pkg/types/types.go
Will log in three stages:
* query preparation: args
* query running: stmt
* query finish: summary
Depends on https://github.com/els0r/goProbe/pull/155 to build. Closes #17 
Example:
```
{
"ts": "2023-08-02T21:46:46.568757798+02:00",
"level": "info",
"msg": "preparing query",
"args": {
"query": "iface",
"ifaces": "any",
"first": "-9000d",
"last": "Wed Aug  2 21:46:46 2023",
"format": "txt",
"sort_by": "bytes",
"num_results": 1000,
"dns_resolution": {
"enabled": false,
"timeout": 1000000000,
"max_rows": 25
},
"max_mem_pct": 60,
"caller": "./goQuery"
}
}
{
"ts": "2023-08-02T21:46:46.574921923+02:00",
"level": "info",
"msg": "running query",
"stmt": {
"ifaces": null,
"label_selector": {
"iface": true
},
"query_type": "iface",
"direction": "bi-directional",
"from": 913405606,
"to": 1691005606, …
```
=> [feature] Log query metadata (args, stmt, summary) in goQuery if configured

pkg/capture/capture_manager.go, pkg/e2etest/e2e_test.go
This will prevent the E2E test from automatically writing to the DB (on top of the manual writeout once all mock data has been processed), thus (hopefully) avoiding any race conditions / results mismatches.
Closes #157
=> [bugfix] Add option to disable scheduled writeouts on CaptureManager and disable for E2E tests

pkg/goDB/storage/gpfile/gpdir.go, pkg/goDB/storage/gpfile/gpfile_test.go
This adds a simple boolean that tracks if a GPDir is open or not. It also adds error handling for crucial paths that might throw an exception when called for unopened GPDirs (and a test for that).
Sidenote: The reason why I couldn't reproduce it at first was that it only occurs when the column (i.e. GPFile) in question has been accessed before (because then the existing GPDir instance assumes it's open upon subsequent calls, otherwise it doesn't).
Closes #143
=> [bugfix] Add explicit tracking / error handling for GDPir Open() being called

cmd/goQuery/cmd/profiling.go, cmd/goQuery/cmd/root.go, cmd/goQuery/pkg/conf/conf.go, pkg/query/args.go
Simple enough, basically re-uses proven code recently removed from goProbe after moving to API based profiling.
Closes #168
=> [feature] Add command line option to enable goQuery profiling

.gitignore, cmd/gpctl/cmd/config.go, cmd/gpctl/cmd/root.go, cmd/gpctl/cmd/status.go, cmd/gpctl/pkg/conf/conf.go
Tasks done:
- New `-t|--timeout` duration command line parameter (new default: `3s`)
- Disables duplicate error output in `status` call
- Disables the emission of usage info if the error is context related (timeout / cancellation)
Closes #177
=> [bugfix] Add timeout parameter and improve error output for gpctl

pkg/api/client/client.go, pkg/api/middleware.go, pkg/api/server/server.go, pkg/goDB/info/hostid.go
@els0r Fairly simple, provides a runtime ID (generated from the nanosecond timestamp + hostID (if available), which should provide enough entropy) which is setup per-binary and then cross-checked via the request headers. If a client queries itself the runtime ID will be identical (because it's the same binary) and hence be rejected (I opted for throwing an error to avoid confusion on the user side - after all it's a configuration error which should be fixed. Since the distributed querier will receive a HTTP 400 it will not retry _and_ simply handle all other requests gracefully while still showing the error and hence prompting the caller to fix the issue).
Using a runtime random ID (instead of using the user-agent and / or the hostID only) this allows us to e.g. still run multiple global …
=> [bugfix] Add API recursion detection using a runtime ID

pkg/capture/buffer.go, pkg/capture/capture.go, pkg/capture/capture_test.go, pkg/capture/capturetypes/packet.go, pkg/capture/capturetypes/parsing_error.go, pkg/capture/flow.go, pkg/e2etest/types.go
@els0r This was easier than anticipated and should provide additional time and space savings during rotations. IMHO it should be fine to reduce whatever overall rotation buffer you've defined by 50% (will still allow more elements in the buffer per rotation). For additional info / benefits, check out the summary in #193 .
Note that this PR is filed against the #171 branch in order to avoid merge conflicts against all the code refactoring. Should be merged only _after_ the referenced PR is merged.
Closes #193
=> [feature] Perform packet parsing in buffer mode to speed up draining

pkg/types/hashmap/aggregate.go, pkg/types/hashmap/hashmap_test.go, pkg/types/hashmap/iterator.go, pkg/types/keyval.go
It turns out that using a functional approach was feasible after all (since after a bit of re-shuffling the code, the overhead for a default non-filter scenario is negligible, and even a filter call doesn't introduce enough overhead to significantly slow down operations on the `AggFlowMap` - after all we're operating on aggregate data already, the core hashmap or even the iterator code isn't touched).
I don't think this rather "edge"-y case and the small penalty warrants over-optimizing as long as the default case complexity is constant. If we need to squeeze out the last few percent we can do so in a future iteration.
```
│    sec/op    │   sec/op     vs base               │
HashMapIterator-4                       982.8µ ± 2%   990.4µ ± 3%       ~ (p=0.436 n=10)
HashMapMetaIterator-4 …
```
=> [feature] Implement functional filter capabilities for aggregate hashmaps

cmd/global-query/pkg/distributed/querier.go, cmd/global-query/pkg/distributed/query.go, cmd/goquery_completion/ifaces.go, pkg/api/goprobe/client/query.go, pkg/goDB/engine/query.go, pkg/query/args.go, pkg/types/types.go
@els0r This is a simple non-breaking extension of the existing `Querier` interface that allows any Querier implementation to optionally support an "any" query (as I've implemented for the current distributed one so that one can select "any" for the `QueryHosts` argument, triggering a query to all configured hosts). It is my understanding that for OSAG you're going to provide custom logic anyway so I assume this doesn't limit you in any way. If I'm wrong please let me know...
Closes #217
=> [feature] Provide QuerierAnyable interface extension to allow querying all available hosts

cmd/global-query/cmd/root.go, cmd/global-query/pkg/distributed/apiclient.go, cmd/global-query/pkg/distributed/querier.go, cmd/global-query/pkg/distributed/query.go, pkg/api/spec/schemas/Result.yaml, pkg/goDB/engine/query.go, pkg/results/result.go
This PR changes the structure of the `Querier` interface, making it arguably more tailored to what it's supposed to do: query hosts in the fleet and return the results for consumption.
The only requirement is that results are put on a channel, leaving choices for handling hosts concurrently up to the individual implementation.
The `APIClientQuerier` has been adjusted to set up concurrent calls to via the goProbe client internally.
=> [feature] Redefinition of the Querier interface

cmd/goQuery/cmd/root.go
When running a query with `--stored-query` from disk, the argument for the location of the query args wasn't taken into account, rendering the flag unusable.
This commit fixes the parameter and extends functionality: in line with other tooling, if `-` is provided as the location of the query args, `goQuery` assumes that they are read from `stdin`. Thus, arguments can now be piped into `goQuery`.
Only to be merged after #234 is on main.
=> [bugfix] Fix --stored-query parameter in goQuery and accept stdin

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/go.yml, examples/config/goprobe-example-config-devcontainer.yaml, pkg/capture/capture.go, pkg/capture/capture_manager.go, pkg/capture/capture_test.go, pkg/capture/flow.go, pkg/capture/metrics.go, pkg/types/keyval.go
This commits add three new metrics to goProbe:
* `goprobe_capture_bytes_total`
* `goprobe_capture_packets_total`
* `goprobe_capture_flows_total`
These are calculated and supplied to prometheus only upon aggregation, which is in line with the approach chosen for the other capture metrics during `status()` calls. The `bytes` and `packets` metrics also have a label `direction=(inbount|outbound)`.
Let's unleash cardinality onto the metrics backends. Metrics of the `capture` subsystem are now vectors with exactly one label: `iface`.
The decision was made to discern better
* on which interface errors/drops occured
* how large the flow maps were
* how much traffic volume was observed per interface
The latter two providing a more detailed understanding of bursts or interfaces over which many …
=> [feature] Add flow map volume/packets metrics to goProbe and introduce iface label

README.md, cmd/goQuery/cmd/help.go, pkg/e2etest/e2e_test.go, pkg/e2etest/types.go, pkg/goDB/conditions/node/filter_direction.go, pkg/goDB/conditions/node/filter_direction_test.go, pkg/goDB/conditions/node/node.go, pkg/goDB/conditions/node/node_test.go, pkg/goDB/conditions/node/parse.go, pkg/goDB/conditions/node/parse_test.go, pkg/goDB/engine/aggregate.go, pkg/goDB/engine/query.go, pkg/types/hashmap/aggregate.go, pkg/types/hashmap/hashmap.go, pkg/types/hashmap/hashmap_test.go, pkg/types/types.go
This PR provides support for traffic direction filters within the `-c` argument of `goQuery`.
The following direction filters are supported: 
`{dir|direction} = {in|inbound|out|outbound|uni|unidirectional|bi|bidirectional}`
A traffic direction filter is allowed to occur as:
- a top-level condition (e.g. `-c "dir = in"`)
- a condition of a top-level conjunct (e.g. `-c "(sip = 127.0.0.1 & port = 22) & dir = out"`)
=> [feature] Support traffic direction filters 

cmd/goquery_completion/common.go, cmd/goquery_completion/conditional.go, cmd/goquery_completion/conditional_test.go, pkg/e2etest/e2e_test.go, pkg/e2etest/types.go, pkg/goDB/conditions/node/filter_direction.go, pkg/goDB/conditions/node/node.go, pkg/goDB/conditions/node/node_test.go, pkg/types/types.go
This PR provides support for autocompletion of the `{dir|direction}` keyword. 
As the `{dir|direction}` keyword imposes some conditions on the structure of the condition string, we want to ensure that:
- keywords are only suggested when they are applicable
- condition strings are automatically terminated if any additional condition would yield an invalid query
Examples: 
- `dir` is suggested for an empty condition string as well as for `(sip = 127.0.0.1 & port = 22) & ` but not for `sip = 127.0.0.1 & port = 22 & ` (`dir`wouldn't occur at the top-level in this case)
- `sip = 127.0.0.1 & dir = inb` yields the automatically terminated condition string `sip = 127.0.0.1 & dir = inbound`
- `dir = in & sip = 127.0.0.1` is automatically terminated
As this PR contains complex filtering logic, we …
=> [feature] Support traffic direction filter autocompletion

pkg/api/api.go, pkg/api/client/client.go, pkg/api/globalquery/server/query.go, pkg/api/globalquery/spec/openapi.yaml, pkg/api/globalquery/spec/schemas/_index.yaml, pkg/api/info.go, pkg/api/server/server.go, pkg/api/spec/openapi.yaml, pkg/api/spec/paths/health.yaml, pkg/api/spec/paths/info.yaml, pkg/api/spec/paths/ready.yaml, pkg/api/spec/schemas/Row.yaml, pkg/api/spec/schemas/ServiceInfo.yaml, pkg/api/spec/schemas/_index.yaml, pkg/api/util.go, pkg/capture/capture_test.go
Provides primitives under `/-/` to:
* show which version is running (and which pod if deployed in kubernetes)
* respond to health probes
* respond to readiness probes
=> [feature] API: Add info endpoints for deployment in k8s

.github/workflows/build-packages.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-push.yml, pkg/capture/capture_test.go, pkg/e2etest/e2e_test.go
This brings down the `push` CI run to <5min. I've decided against removing some of the individual tests (using `-short` and the likes) because the _runtime_ of the whole test suite is / was not the limiting factor and I don't see the need to introduce further complexity for the sake of a few seconds of runtime. 
We're now mostly bound by the initial fetch / build of the package, which can't really be sped up I guess.
I've also taken the liberty of doing some cleanup of the output, reducing the terribly high verbosity from some of the tests.
Closes #249
=> [feature] Improve build pipeline speed

cmd/legacy/main.go, pkg/goDB/storage/gpfile/gpdir.go
This should make in-situ DB conversion much, much easier to facilitate. The changed processing order in combination with the ability to trim data older than a certain timestamp (only affects whole directories / days so we can't "fracture" data) should support the following `YOLO` upgrade flow:
1. Stop `goProbe v3`
2. Upgrade package
3. Run `legacy` tool against `v3` DB (limit to e.g. the last 7 days or so, depending on the volume / patch speed required)
4. Start `goProbe v4` (against newly converted DB)
The patch is done at this point. `goProbe v4` can happily write to the converted partial DB (as it contains all the most recent data) and the patch can terminate.
Immediately after the upgrade completed, re-run the `legacy` tool with the same parameters (maybe less cores as there's no rush …
=> [feature] Optimize legacy v4 conversion tool for large DBs

cmd/goQuery/cmd/root.go, pkg/api/query.go, pkg/query/args.go, pkg/query/args_test.go
Most were easy enough, just one note: The `.(type)` assertion replacement becomes really nasty if you have a lot of possible types for an error (which luckily isn't the case here) because this cannot be done safely with a switch statement. Instead, one would have to check against each type one by one using `errors.As()`. So in conclusion: Try to avoid... :wink:
Closes #255
=> [bugfix] Remove error type assertion antipattern

pkg/goDB/DBWorkManager.go
Note: This might come back to us at some point (e.g. if we encounter some strange corrupted DBs, which might prevent querying, but TBH I'd rather see this instead of having the call silently return incomplete / corrupt data).
Closes #254
=> [bugfix] Add missing error handling during DB walk

cmd/legacy/main.go
Adds additional cross-checks for the input DB tree.
Closes #263
=> [bugfix][feature] Increase safety of legacy DB conversion tool

cmd/goProbe/config/monitor.go, cmd/gpctl/cmd/config.go, cmd/gpctl/cmd/status.go, pkg/api/goprobe/api.go, pkg/api/goprobe/client/config.go, pkg/api/goprobe/spec/schemas/ConfigUpdateResponse.yaml, pkg/api/goprobe/spec/schemas/IfaceChange.yaml, pkg/capture/capture_manager.go, pkg/capture/capturetypes/config.go, pkg/types/shellformat/shellformat.go, pkg/types/shellformat/shellformat_test.go
Extended API now provides information about success of all interface config changes (using a struct instead of a simple string for each one). Looks like this:
Note: If an interface _update_ fails during the `disable` step but then succeeds in the subsequent `enable` step it will show up as successful.
Closes #225
=> [feature] Improve config reload change feedback

cmd/goQuery/cmd/root.go, pkg/query/args.go, pkg/types/types.go
This gets rid of the crashes. However TBH I'm not supa happy with the current setup, mostly because it's inconsistent. There are places where it's asserted if an error is a `Prettier`, then a few lines later an error is generated that just assumes to be. We should revisit the whole console output / pretty / non-pretty concept IMHO at some point (and be as generic as possible, adding a few helper functions maybe to make our lives easier).
=> [bugfix] Remove cyclic calls for Prettier / Pretty() interface & implementation

pkg/goDB/DBWorkManager.go, pkg/goDB/engine/query.go
Moves handling of context termination down one layer into the processing loop to be able to cancel more quickly.
Closes #273
=> [bugfix] Improve handling of context cancel in DBWorkManager to be more responsive

pkg/capture/flow.go, pkg/capture/packet_test.go
Fixed potential out-of-bounds access and added test for the encountered special (invalid) IP packet scenario.
I'm also trying to capture an actual small `pcap` file on the host in question to get a sample for the E2E tests, but didn't happen again so far... :see_no_evil: 
Performance is actually slightly better (probably because the hint now is more accurate for everything that happens in the function):
```
│ /tmp/old.txt │            /tmp/new.txt            │
│    sec/op    │   sec/op     vs base               │
Population/0.0.0.0:68->255.255.255.255:67_17_0-4    9.681n ± 1%   9.514n ± 1%  -1.73% (p=0.000 n=25)
```
Nice catch!
Closes #279
=> [bugfix] Fix access beyond IP layer bounds if packet stops right after it

pkg/capture/capturetypes/parsing_error.go, pkg/capture/capturetypes/parsing_error_test.go, pkg/capture/metrics.go, pkg/e2etest/e2e_test.go, pkg/e2etest/types.go
As expected, related to a value receiver :see_no_evil:
Took the opportunity to improve the whole E2E suite by further consistency checks (now also cross-checking the most important Prometheus counters).
Closes #281
=> [bugfix] Fix incorrect Prometheus error counters

pkg/goDB/DBWorkManager.go, pkg/goDB/engine/query.go, pkg/goDB/engine/query_test.go, pkg/query/args.go, pkg/query/args_test.go, pkg/types/iface.go
The side-effect before was that it wasn't set, leading to the interface attribute not being present in the output when >1 interfaces were part of a query.
Also:
* instrument each per-interface processing with a span
Closes #288
=> [bugfix] Make sure that the interface selector is set on `args.Prepare()`

cmd/goQuery/cmd/help.go, cmd/goQuery/cmd/help_test.go, pkg/query/time.go, pkg/query/time_test.go
Now looks like this (always uses current timestamp of help call):
```
...
-f, --first string                        Upper/lower bound on flow timestamp
DEFAULTS
--first will default to the last 30 days if not provided. In case
a "time" attribute is involved (e.g. for "time" or "raw" queries),
the default is lowered to the last 24 hours. This is to protect
against accidentally querying the entire database.
--last will default to the current time if not provided
ALLOWED FORMATS
2024-04-14T12:07:21+02:00                     RFC3339
Sun Apr 14 12:07:21 2024                      ANSIC
Sun Apr 14 12:07:21 +0200 2024                RUBY DATE
14 Apr 24 12:07 +0200                         RFC822 with numeric zone
Sun, 14 Apr 2024 12:07:21 +0200               RFC1123 with numeric zone
2024-04-14 …
```
=> [bugfix] Fix help output for supported timestamps (to actually support all of them)

cmd/goQuery/cmd/root.go, pkg/api/client/client.go
Guards against situations where `goQuery`'s `--query.timeout` parameter is ignored for global queries. It sets the default timeout to 30 minutes to provide some guardrail against long-running requests.
Closes #305
=> [bugfix] Remove default 30 second timeout in client

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .gitignore, cmd/goQuery/cmd/root.go, cmd/goQuery/pkg/conf/conf.go, pkg/query/dns/dns.go, pkg/query/dns/dns_test.go, pkg/query/query.go, pkg/results/TablePrinter.go, pkg/results/print.go, pkg/results/result.go
Separates console printing into the following stages (where `[ ]` denotes optional):
* [ error logging for failed hosts in distributed query ]
* query output (the flow table)
* summary
The summary in its longest form (e.g. a distributed query with a reverse DNS lookup and a tracing infrastructure in place) will look like:
```
Timespan           : [2024-04-15 20:44:35, 2024-04-15 21:46:37] (1h2m0s)
Interfaces / Hosts : 280 queried on 248 hosts: 114 ok / 0 empty / 134 error
Sorted by          : accumulated data volume (sent and received)
Query stats        : displayed top 25 hits out of 827 in 13.32s
Conditions         : dport = 443
Trace ID           : cff4115b6080bce9c0c233b560acd71e
```
* Interface names are only printed if the query attribute doesn't include the interface
* removes the …
=> [feature] Reduce verbosity of interface listing and host statuses in global query output

go.mod, go.sum, pkg/goDB/DBWorkManager.go
=> [bugfix] Fix potential panic for corrupted goDB files and improve handling of error cases

go.mod, go.sum, pkg/capture/buffer.go, pkg/capture/capture.go, pkg/capture/capture_manager.go, pkg/capture/capture_test.go
First attempt at fixing (or at least improving) the potential deadlocks. I still wasn't able to reproduce the issue to its full extend, but at least one of the observed crashes I confirmed to be addressed by this. The issue will remain open after merging this for further assessment.
=> [bugfix] Integrate improved three-point lock for capture routines and improve concurrency patterns

cmd/goQuery/cmd/root.go, cmd/goQuery/pkg/conf/conf.go, pkg/goDB/DBWorkManager.go, pkg/goDB/engine/aggregate.go, pkg/goDB/engine/query.go, pkg/goDB/storage/storage.go
This commit provides a _simple_ (!) keep-alive mechanism, which can be used to inform the caller of `goQuery` that a query is still running.
The `--query.keepalive` or `-k` shorthand specifies an interval after which the caller gets a query processing update. By default, it is 0, which equates no keep alive.
```nothing
ts=2024-05-23T14:39:01.715Z level=info msg="processed work dir" version=devel worker.id=7 iface=eth0 dir=.db/eth0/2024/03/1710460800 stats.bytes_loaded=0 stats.bytes_decompressed=3848214 stats.blocks_processed=17860 stats.blocks_corrupted=0 stats.directories_processed=31 stats.workloads=1
ts=2024-05-23T14:39:01.931Z level=info msg="processed workload" version=devel iface=eth0 dir=.db/eth0 stats.bytes_loaded=0 stats.bytes_decompressed=7357134 stats.blocks_processed=68980 …
```
=> [feature] Keep Alive for goQuery: log progress during query execution

pkg/capture/buffer.go, pkg/capture/buffer_test.go, pkg/capture/capture.go, pkg/capture/capture_manager.go, pkg/capture/capture_test.go
No functional changes, refactor / cleanup only.
Closes #320
=> [feature] Refactor local buffer / memory pool handling for CaptureManager

pkg/goDB/DBWorkManager.go
=> [bugfix] Add additional safeguards and logging for unexpectedly empty Bitpack columns

cmd/global-query/pkg/distributed/query.go, cmd/goQuery/cmd/root.go, cmd/goQuery/pkg/conf/conf.go, go.mod, go.sum, pkg/e2etest/e2e_test.go, pkg/formatting/format.go, pkg/goDB/DBWorkManager.go, pkg/goDB/engine/aggregate.go, pkg/goDB/engine/query.go, pkg/goDB/godb_test.go, pkg/results/TablePrinter.go, pkg/results/result.go, pkg/types/hashmap/aggregate.go, pkg/types/workload/stats.go
=> [feature] Goquery: less verbose and frequent keep-alive messages

.gitignore, cmd/goProbe/goProbe.go, pkg/api/goprobe/server/server.go, pkg/api/query_api_ops.go
See comments in PR code for details.
Closes #340
=> [bugfix] Fix missing query route and DB path parsing in goQuery API

cmd/global-query/pkg/distributed/query.go, pkg/types/columns.go, pkg/types/columns_test.go
This fixes a bug where queries such as `"sip, dip,dport"` wouldn't be evaluated only because of the whitespace in them.
The implicit assumption was that this wouldn't happen if called from the command line (due to the arguments being evaluated as `[]string{..., "sip,", "dip,dport"}`. For the `json` case, this is very much a valid way of passing the arguments.
Sanitization is applied both in goQuery (to local DB) and global-query.
Closes #347 .
=> [bugfix] Strip whitespace from `args.Query` when sanitizing it

pkg/goDB/DBWorkManager.go, pkg/goDB/Query.go, pkg/goDB/engine/aggregate.go, pkg/goDB/engine/query.go, pkg/types/workload/stats.go
Addresses the following:
- Disentangles the keepalive from the aggregation step (which may just receive new maps / workloads at a too slow rate to ensure sufficient keepalive frequency)
- Cleanup interaction by moving keepalive tracking into the query
- Remove `iface` from keepalive signal (i.e. log line) since it is / was pointless anyway (as it depends solely on which map was being processed at the time of the signa and hence is totally random)
Closes #350
=> [bugfix] Improve keepalive signal for queries

cmd/goQuery/cmd/root.go, pkg/goDB/engine/query.go, pkg/query/args.go
Turns out not _everything_ is validated when reading a serialized query from disk / JSON. In particular, there is no check if said query attempts to perform a live query against a local DB instead of an API (which caused the panic due a missing `CaptureManager`). This is now caught in two places (firstly preventing such queries to run in the first place and secondly gracefully skipping the query with an error message should it happen anyway).
=> [bugfix] Ensure that no live queries can be performed against a local DB

.devcontainer/Dockerfile
'RUN go install golang.org/x/tools/gopls@latest' fails due to latest gopls requiring 1.23 or higher
=> [trivial] Bump dev image version to 1.23

README.md
This seems to be the only remaining broken thing regarding the `v4` package migration (and technically not even related to that, just saw then when reviewing the `README`), aside from that everything is fine. Kudos again to @denysvitali for tackling this!
Closes #215
=> [bugfix] Fix GitHub actions badge

presentations/2025/goprobe_bern_meetup/Makefile, presentations/2025/goprobe_bern_meetup/package.json, presentations/2025/goprobe_bern_meetup/slides.md
Adds some convenience stuff for PDF rendering (the browser exporter is buggy, so use the CLI via `Makefile`) and provide PDF version of Bern Go Meetup 2025 slides.
=> [feature] Simplify slide exporting feature and provide PDF

cmd/goQuery/cmd/root.go, pkg/goDB/engine/query.go, pkg/results/TablePrinter.go
Instead of breaking out of the table processing if no data was found the table will now still be printed, but the rows and their headers are simply omitted if no rows were received, leading to a footer-only output:
```
└─ $ ▶ ./goQuery   -d /home/fako/Downloads/db -f -1d -n 10 -i any sip,dip
Status "missing_data": no data available for the specified interface(s) / time range (maybe goProbe was not running)
Timespan    : [2025-04-25 11:31:49, 2025-04-26 11:31:49] (1d0s)
Interface   : 23 queried
Sorted by   : accumulated data volume (sent and received)
Query stats : displayed top 0 hits out of 0 in 2ms
```
Side-note: At some point we should refactor the whole printer concept, it's a bit contrived (also has several fundamental code issues caught by today's linter configs).
Closes #360
=> [bugfix] Print table footer on console even if no data was found

pkg/api/query_api_ops.go, pkg/api/query_test.go
There was an error in the error condition.
Adds API test for this part of `/_query/validate` using `humatest`.
=> [bugfix] Fix validation of query_hosts for distributed querier

cmd/global-query/pkg/distributed/query.go, cmd/global-query/pkg/distributed/query_test.go, pkg/api/globalquery/server/server.go, pkg/api/query.go, pkg/api/query_api_ops.go, pkg/results/result.go, pkg/types/types.go
Addresses a bug where `rows` were `null` if part of a `partialResult` in an event stream.
The amount of rows are guarded by the `limit` parameter, as well as a maximum of 100 rows per partial result. This is to save bandwidth when streaming results for queries having a large limit set.
The logic for producing the final result is now consolidated and shared between the `sse.Send` part of the query code and the finalization code. All results manipulation happens inside `run` now.
Finally, the `distributed` package adds tests to verify basic behavior as well as the above for SSE sends.
Closes #401 .
=> [bugfix] Make sure that partial results also include rows
